### ISSUE TITLE
Scroll glitch in mobile view

### ISSUE THREAD

**Issue by saurabhshalu** [saurabhshalu/saurabhshalu.github.io#1]
There is a scroll glitch in my portfolio when you open it in mobile. 
In the project section, swipe left and swipe right is working properly for the cards, but when someone tries to scroll the webpage up or down from the card, it does not move.

Any help would be appreciated.

**Comment by oneofthedevs** [comment]
I can take a look, assign me

**Comment by saurabhshalu** [comment]
> I can take a look, assign me

okay

**Comment by saurabhshalu** [comment]
Done
